{batch_size: 512, epochs: 30, latent_dim: 2, latent_factor: 1, latent_loss: kl_divergence,
  model_name: mnist_cnn_shallow, model_type: variational_autoencoder, name: vae_rf_1000,
  optimizer: adam, reconstruction_factor: 1000, reconstruction_loss: binary_crossentropy}
